### ISSUE TITLE
Need config example for mockrunner-jms

### ISSUE THREAD

**Issue by mariaklimenko** [mockrunner/mockrunner#47]
Hello! I am newbie in Java and struggle with mockrunner-jms setup. The example in the project doesn't contain config files, so I'm getting the following exception when launching PrintMessageServletTest, failing block:
    protected void setUp() throws Exception
    {
        super.setUp();
        ejbModule = createEJBTestModule();
        ejbModule.bindToContext("java:ConnectionFactory",
                getJMSMockObjectFactory().getMockQueueConnectionFactory());
        queue = getDestinationManager().createQueue("testQueue");
        ejbModule.bindToContext("queue/testQueue", queue);
        servletModule = createServletTestModule();
        servletModule.createServlet(PrintMessageServlet.class);
    }
As far as I understand, I need to put some sonfig in my classpath. Please, help me to get mockrunner-jms example running. If you want, I then can create a little maven project with this example and help other people to onboard this more rapidly...

"C:\Program Files\Java\jdk1.8.0_121\bin\java" -ea -Didea.launcher.port=7535 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.4\lib\idea_rt.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.4\plugins\junit\lib\junit-rt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\rt.jar;C:\Users\Maria\IdeaProjects\jeta\jeta-master\target\test-classes;C:\Users\Maria\IdeaProjects\jeta\jeta-master\target\classes;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-java\3.2.0\selenium-java-3.2.0.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.2.0\selenium-chrome-driver-3.2.0.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.2.0\selenium-remote-driver-3.2.0.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-api\3.2.0\selenium-api-3.2.0.jar;C:\Users\Maria\.m2\repository\cglib\cglib-nodep\3.2.4\cglib-nodep-3.2.4.jar;C:\Users\Maria\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\Maria\.m2\repository\org\apache\httpcomponents\httpclient\4.5.2\httpclient-4.5.2.jar;C:\Users\Maria\.m2\repository\org\apache\httpcomponents\httpcore\4.4.4\httpcore-4.4.4.jar;C:\Users\Maria\.m2\repository\net\java\dev\jna\jna-platform\4.1.0\jna-platform-4.1.0.jar;C:\Users\Maria\.m2\repository\net\java\dev\jna\jna\4.1.0\jna-4.1.0.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.2.0\selenium-edge-driver-3.2.0.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.2.0\selenium-firefox-driver-3.2.0.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.2.0\selenium-ie-driver-3.2.0.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.2.0\selenium-opera-driver-3.2.0.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\3.2.0\selenium-safari-driver-3.2.0.jar;C:\Users\Maria\.m2\repository\com\codeborne\phantomjsdriver\1.4.0\phantomjsdriver-1.4.0.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\htmlunit-driver\2.24\htmlunit-driver-2.24.jar;C:\Users\Maria\.m2\repository\org\seleniumhq\selenium\selenium-support\3.2.0\selenium-support-3.2.0.jar;C:\Users\Maria\.m2\repository\org\hamcrest\hamcrest-library\1.3\hamcrest-library-1.3.jar;C:\Users\Maria\.m2\repository\net\sourceforge\htmlunit\htmlunit\2.24\htmlunit-2.24.jar;C:\Users\Maria\.m2\repository\org\apache\httpcomponents\httpmime\4.5.2\httpmime-4.5.2.jar;C:\Users\Maria\.m2\repository\net\sourceforge\htmlunit\htmlunit-core-js\2.23\htmlunit-core-js-2.23.jar;C:\Users\Maria\.m2\repository\net\sourceforge\htmlunit\neko-htmlunit\2.24\neko-htmlunit-2.24.jar;C:\Users\Maria\.m2\repository\net\sourceforge\cssparser\cssparser\0.9.21\cssparser-0.9.21.jar;C:\Users\Maria\.m2\repository\org\w3c\css\sac\1.3\sac-1.3.jar;C:\Users\Maria\.m2\repository\org\eclipse\jetty\websocket\websocket-client\9.2.20.v20161216\websocket-client-9.2.20.v20161216.jar;C:\Users\Maria\.m2\repository\org\eclipse\jetty\jetty-util\9.2.20.v20161216\jetty-util-9.2.20.v20161216.jar;C:\Users\Maria\.m2\repository\org\eclipse\jetty\jetty-io\9.2.20.v20161216\jetty-io-9.2.20.v20161216.jar;C:\Users\Maria\.m2\repository\org\eclipse\jetty\websocket\websocket-common\9.2.20.v20161216\websocket-common-9.2.20.v20161216.jar;C:\Users\Maria\.m2\repository\org\eclipse\jetty\websocket\websocket-api\9.2.20.v20161216\websocket-api-9.2.20.v20161216.jar;C:\Users\Maria\.m2\repository\junit\junit\4.12\junit-4.12.jar;C:\Users\Maria\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Maria\.m2\repository\info\cukes\cucumber-junit\1.2.5\cucumber-junit-1.2.5.jar;C:\Users\Maria\.m2\repository\info\cukes\cucumber-core\1.2.5\cucumber-core-1.2.5.jar;C:\Users\Maria\.m2\repository\info\cukes\cucumber-html\0.2.3\cucumber-html-0.2.3.jar;C:\Users\Maria\.m2\repository\info\cukes\cucumber-java\1.2.5\cucumber-java-1.2.5.jar;C:\Users\Maria\.m2\repository\info\cukes\cucumber-picocontainer\1.2.5\cucumber-picocontainer-1.2.5.jar;C:\Users\Maria\.m2\repository\info\cukes\cucumber-jvm-deps\1.0.5\cucumber-jvm-deps-1.0.5.jar;C:\Users\Maria\.m2\repository\info\cukes\gherkin\2.12.2\gherkin-2.12.2.jar;C:\Users\Maria\.m2\repository\org\picocontainer\picocontainer\2.15\picocontainer-2.15.jar;C:\Users\Maria\.m2\repository\com\sun\jersey\jersey-client\1.8\jersey-client-1.8.jar;C:\Users\Maria\.m2\repository\com\sun\jersey\jersey-core\1.8\jersey-core-1.8.jar;C:\Users\Maria\.m2\repository\com\sun\jersey\jersey-json\1.17\jersey-json-1.17.jar;C:\Users\Maria\.m2\repository\org\codehaus\jettison\jettison\1.1\jettison-1.1.jar;C:\Users\Maria\.m2\repository\com\sun\xml\bind\jaxb-impl\2.2.3-1\jaxb-impl-2.2.3-1.jar;C:\Users\Maria\.m2\repository\javax\xml\bind\jaxb-api\2.2.2\jaxb-api-2.2.2.jar;C:\Users\Maria\.m2\repository\javax\xml\stream\stax-api\1.0-2\stax-api-1.0-2.jar;C:\Users\Maria\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;C:\Users\Maria\.m2\repository\org\codehaus\jackson\jackson-core-asl\1.9.2\jackson-core-asl-1.9.2.jar;C:\Users\Maria\.m2\repository\org\codehaus\jackson\jackson-mapper-asl\1.9.2\jackson-mapper-asl-1.9.2.jar;C:\Users\Maria\.m2\repository\org\codehaus\jackson\jackson-jaxrs\1.9.2\jackson-jaxrs-1.9.2.jar;C:\Users\Maria\.m2\repository\org\codehaus\jackson\jackson-xc\1.9.2\jackson-xc-1.9.2.jar;C:\Users\Maria\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Maria\.m2\repository\io\github\bonigarcia\webdrivermanager\1.6.0\webdrivermanager-1.6.0.jar;C:\Users\Maria\.m2\repository\org\slf4j\slf4j-api\1.7.12\slf4j-api-1.7.12.jar;C:\Users\Maria\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Maria\.m2\repository\com\google\code\gson\gson\2.3.1\gson-2.3.1.jar;C:\Users\Maria\.m2\repository\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\Maria\.m2\repository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;C:\Users\Maria\.m2\repository\org\rauschig\jarchivelib\0.7.1\jarchivelib-0.7.1.jar;C:\Users\Maria\.m2\repository\org\apache\commons\commons-compress\1.9\commons-compress-1.9.jar;C:\Users\Maria\.m2\repository\org\jsoup\jsoup\1.9.2\jsoup-1.9.2.jar;C:\Users\Maria\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\Maria\.m2\repository\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\Maria\.m2\repository\com\mockrunner\mockrunner-ejb\1.1.2\mockrunner-ejb-1.1.2.jar;C:\Users\Maria\.m2\repository\com\mockrunner\mockrunner-core\1.1.2\mockrunner-core-1.1.2.jar;C:\Users\Maria\.m2\repository\com\kirkk\jaranalyzer\1.2\jaranalyzer-1.2.jar;C:\Users\Maria\.m2\repository\bcel\bcel\5.1\bcel-5.1.jar;C:\Users\Maria\.m2\repository\regexp\regexp\1.2\regexp-1.2.jar;C:\Users\Maria\.m2\repository\jakarta-regexp\jakarta-regexp\1.4\jakarta-regexp-1.4.jar;C:\Users\Maria\.m2\repository\ant\ant\1.6.5\ant-1.6.5.jar;C:\Users\Maria\.m2\repository\commons-beanutils\commons-beanutils\1.9.2\commons-beanutils-1.9.2.jar;C:\Users\Maria\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\Maria\.m2\repository\org\mockejb\mockejb\0.6-beta2\mockejb-0.6-beta2.jar;C:\Users\Maria\.m2\repository\cglib\cglib-full\2.0.2\cglib-full-2.0.2.jar;C:\Users\Maria\.m2\repository\com\mockrunner\mockrunner-jdk1.5-j2ee1.3\0.4\mockrunner-jdk1.5-j2ee1.3-0.4.jar;C:\Users\Maria\.m2\repository\commons-digester\commons-digester\1.8\commons-digester-1.8.jar;C:\Users\Maria\.m2\repository\commons-logging\commons-logging\1.0.4\commons-logging-1.0.4.jar;C:\Users\Maria\.m2\repository\commons-validator\commons-validator\1.3.1\commons-validator-1.3.1.jar;C:\Users\Maria\.m2\repository\oro\oro\2.0.8\oro-2.0.8.jar;C:\Users\Maria\.m2\repository\jdom\jdom\1.0\jdom-1.0.jar;C:\Users\Maria\.m2\repository\nekohtml\nekohtml\0.9.5\nekohtml-0.9.5.jar;C:\Users\Maria\.m2\repository\javax\servlet\servlet-api\2.3\servlet-api-2.3.jar;C:\Users\Maria\.m2\repository\struts\struts\1.2.9\struts-1.2.9.jar;C:\Users\Maria\.m2\repository\commons-fileupload\commons-fileupload\1.0\commons-fileupload-1.0.jar;C:\Users\Maria\.m2\repository\antlr\antlr\2.7.2\antlr-2.7.2.jar;C:\Users\Maria\.m2\repository\xalan\xalan\2.5.1\xalan-2.5.1.jar;C:\Users\Maria\.m2\repository\xerces\xercesImpl\2.9.0\xercesImpl-2.9.0.jar;C:\Users\Maria\.m2\repository\xml-apis\xml-apis\1.3.04\xml-apis-1.3.04.jar;C:\Users\Maria\.m2\repository\javax\jms\jms\1.1\jms-1.1.jar;C:\Users\Maria\.m2\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;C:\Users\Maria\.m2\repository\javax\transaction\javax.transaction-api\1.2\javax.transaction-api-1.2.jar;C:\Users\Maria\.m2\repository\org\glassfish\main\ejb\javax.ejb\3.1.2\javax.ejb-3.1.2.jar;C:\Users\Maria\.m2\repository\org\glassfish\main\transaction\javax.transaction\3.1.2\javax.transaction-3.1.2.jar;C:\Users\Maria\.m2\repository\org\glassfish\main\javaee-api\javax.annotation\3.1.2\javax.annotation-3.1.2.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.jetamocks.jms.PrintMessageServletTest
javax.naming.NameNotFoundException: Name java:/ConnectionFactory not found. 
	at org.mockejb.jndi.MockContext.lookup(MockContext.java:543)
	at org.mockejb.jndi.MockContext$$FastClassByCGLIB$$8f78c5.invoke(<generated>)
	at net.sf.cglib.reflect.FastMethod.invoke(FastMethod.java:57)
	at org.mockejb.interceptor.InterceptorInvoker$CglibMethodInvoker.intercept(InterceptorInvoker.java:95)
	at org.mockejb.interceptor.InvocationContext.proceed(InvocationContext.java:177)
	at org.mockejb.interceptor.InterceptorInvoker.invoke(InterceptorInvoker.java:53)
	at org.mockejb.interceptor.InterceptableProxy.intercept(InterceptableProxy.java:58)
	at $javax.naming.Context$$EnhancerByCGLIB$$f6e73895.lookup(<generated>)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.jetamocks.jms.PrintMessageServlet.init(PrintMessageServlet.java:36)
	at javax.servlet.GenericServlet.init(GenericServlet.java:258)
	at com.mockrunner.servlet.ServletTestModule.setServlet(ServletTestModule.java:85)
	at com.mockrunner.servlet.ServletTestModule.createServlet(ServletTestModule.java:51)
	at com.jetamocks.jms.PrintMessageServletTest.setUp(PrintMessageServletTest.java:32)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

com.mockrunner.base.VerifyFailedException: actual output: Error sending print request for 1 does not match expected output

	at com.mockrunner.base.HTMLOutputModule.verifyOutputContains(HTMLOutputModule.java:129)
	at com.jetamocks.jms.PrintMessageServletTest.testServletResponse(PrintMessageServletTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

javax.naming.NameNotFoundException: Name java:/ConnectionFactory not found. 
	at org.mockejb.jndi.MockContext.lookup(MockContext.java:543)
	at org.mockejb.jndi.MockContext$$FastClassByCGLIB$$8f78c5.invoke(<generated>)
	at net.sf.cglib.reflect.FastMethod.invoke(FastMethod.java:57)
	at org.mockejb.interceptor.InterceptorInvoker$CglibMethodInvoker.intercept(InterceptorInvoker.java:95)
	at org.mockejb.interceptor.InvocationContext.proceed(InvocationContext.java:177)
	at org.mockejb.interceptor.InterceptorInvoker.invoke(InterceptorInvoker.java:53)
	at org.mockejb.interceptor.InterceptableProxy.intercept(InterceptableProxy.java:58)
	at $javax.naming.Context$$EnhancerByCGLIB$$f6e73895.lookup(<generated>)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.jetamocks.jms.PrintMessageServlet.init(PrintMessageServlet.java:36)
	at javax.servlet.GenericServlet.init(GenericServlet.java:258)
	at com.mockrunner.servlet.ServletTestModule.setServlet(ServletTestModule.java:85)
	at com.mockrunner.servlet.ServletTestModule.createServlet(ServletTestModule.java:51)
	at com.jetamocks.jms.PrintMessageServletTest.setUp(PrintMessageServletTest.java:32)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

com.mockrunner.base.VerifyFailedException: Expected 3 messages received by queue testQueue, received 0 messages

	at com.mockrunner.jms.JMSTestModule.verifyNumberOfReceivedQueueMessages(JMSTestModule.java:2450)
	at com.mockrunner.jms.JMSTestCaseAdapter.verifyNumberOfReceivedQueueMessages(JMSTestCaseAdapter.java:1179)
	at com.jetamocks.jms.PrintMessageServletTest.testSendAndReceive(PrintMessageServletTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

javax.naming.NameNotFoundException: Name java:/ConnectionFactory not found. 
	at org.mockejb.jndi.MockContext.lookup(MockContext.java:543)
	at org.mockejb.jndi.MockContext$$FastClassByCGLIB$$8f78c5.invoke(<generated>)
	at net.sf.cglib.reflect.FastMethod.invoke(FastMethod.java:57)
	at org.mockejb.interceptor.InterceptorInvoker$CglibMethodInvoker.intercept(InterceptorInvoker.java:95)
	at org.mockejb.interceptor.InvocationContext.proceed(InvocationContext.java:177)
	at org.mockejb.interceptor.InterceptorInvoker.invoke(InterceptorInvoker.java:53)
	at org.mockejb.interceptor.InterceptableProxy.intercept(InterceptableProxy.java:58)
	at $javax.naming.Context$$EnhancerByCGLIB$$f6e73895.lookup(<generated>)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.jetamocks.jms.PrintMessageServlet.init(PrintMessageServlet.java:36)
	at javax.servlet.GenericServlet.init(GenericServlet.java:258)
	at com.mockrunner.servlet.ServletTestModule.setServlet(ServletTestModule.java:85)
	at com.mockrunner.servlet.ServletTestModule.createServlet(ServletTestModule.java:51)
	at com.jetamocks.jms.PrintMessageServletTest.setUp(PrintMessageServletTest.java:32)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

com.mockrunner.base.VerifyFailedException: No QueueConnection present.

	at com.mockrunner.jms.JMSTestModule.verifyQueueConnectionStarted(JMSTestModule.java:769)
	at com.mockrunner.jms.JMSTestCaseAdapter.verifyQueueConnectionStarted(JMSTestCaseAdapter.java:451)
	at com.jetamocks.jms.PrintMessageServletTest.testInitPrintMessageReceiver(PrintMessageServletTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code -1

**Comment by mariaklimenko** [comment]
I found out how launch jms examples

**Comment by mariaklimenko** [comment]
It would be helpful for others if you put the following class into example folder 
import com.mockrunner.ejb.EJBTestModule;
import com.mockrunner.jms.JMSTestCaseAdapter;
import com.mockrunner.mock.jms.MockObjectMessage;
import com.mockrunner.mock.jms.MockQueue;
import com.mockrunner.mock.jms.MockTextMessage;
import com.mockrunner.servlet.ServletTestModule;

import javax.jms.*;

public class PrintMessageServletTest extends JMSTestCaseAdapter
{
    private EJBTestModule ejbModule;
    private ServletTestModule servletModule;
    private MockQueue queue;
    private PrintMessageServlet servlet;

    protected void setUp() throws Exception
    {
        /* ApplicationContext ctx = new ClassPathXmlApplicationContext(
                "classpath:jemosJmsTest-appContext.xml");

        jmsTemplate = ctx.getBean(JmsTemplate.class);
        mockDestinationManager = ctx.getBean(DestinationManager.class);
        connectionFactory = ctx.getBean(QueueConnectionFactory.class);

        System.out.println("Received message: ");  */


        super.setUp();
        servlet = new PrintMessageServlet();
        ejbModule = createEJBTestModule();
        ejbModule.bindToContext("java:/ConnectionFactory", getJMSMockObjectFactory().getMockQueueConnectionFactory());
        queue = getDestinationManager().createQueue("testQueue");
        ejbModule.bindToContext("queue/testQueue", queue);
        servletModule = createServletTestModule();
        servletModule.createServlet(PrintMessageServlet.class);
    }

    public void testInitPrintMessageReceiver() throws Exception
    {
        verifyQueueConnectionStarted();
        verifyNumberQueueSessions(1);
        verifyNumberQueueReceivers(0, "testQueue", 1);
        QueueReceiver receiver = getQueueTransmissionManager(0).
                getQueueReceiver("testQueue");
        assertTrue(receiver.getMessageListener() instanceof
                PrintMessageListener);
    }

    public void testSendAndReceive() throws Exception
    {
        servletModule.addRequestParameter("customerId", "1");
        servletModule.doGet();
        servletModule.addRequestParameter("customerId", "2");
        servletModule.doGet();
        servletModule.addRequestParameter("customerId", "3");
        servletModule.doGet();
        verifyNumberOfReceivedQueueMessages("testQueue", 3);
        verifyAllReceivedQueueMessagesAcknowledged("testQueue");
        verifyReceivedQueueMessageEquals("testQueue", 0,
                new MockTextMessage("1"));
        verifyReceivedQueueMessageEquals("testQueue", 1,
                new MockTextMessage("2"));
        verifyReceivedQueueMessageEquals("testQueue", 2,
                new MockTextMessage("3"));
        QueueSender sender = getQueueTransmissionManager(0).
                createQueueSender(queue);
        sender.send(new MockObjectMessage(new Integer(3)));
        verifyNumberOfReceivedQueueMessages("testQueue", 4);
        verifyReceivedQueueMessageAcknowledged("testQueue", 3);
        verifyNumberOfCurrentQueueMessages("testQueue", 0);
    }

    public void testServletResponse() throws Exception
    {
        servletModule.setCaseSensitive(false);
        servletModule.addRequestParameter("customerId", "1");
        servletModule.doGet();
        servletModule.verifyOutputContains("successfully");
        servletModule.clearOutput();
        getJMSMockObjectFactory().getMockQueueConnectionFactory().
                setJMSException(new JMSException("TestException"));
        servletModule.doGet();
        servletModule.verifyOutputContains("error");
    }
}
