### ISSUE TITLE
Calling MockDatabaseMetaData.getColumns twice returns the same ResultSet object

### ISSUE THREAD

**Issue by kz282** [mockrunner/mockrunner#73]
Hi,

I have a test case where lots of DatabaseMetaData info are queried. I have found that querying the same column info twice makes the second query fail. 

I have narrowed it to a test case:

```
    /**
     * Looks like MockDatabaseMetaData.getColumns method returns the same ResultSet if called twice.
     * They should only have the same content but with different cursor and other internals. 
     * 
     * Moving the cursor before the first row makes this test case pass, but returning clones of the result sets fixes this issue in real.
     * @throws SQLException 
     */
    public void testColumns2() throws SQLException
    {
        MockDatabaseMetaData metaData = new MockDatabaseMetaData();
        MockResultSet testResult = new MockResultSet("id");
        testResult.addColumn("COLUMN_NAME", new Object[]{"mycolumn"});
        testResult.addColumn("DATA_TYPE", new Object[]{java.sql.Types.INTEGER});
        metaData.setColumns(null, "public", "mytable", "mycolumn", testResult);
        
        ResultSet columns1 = metaData.getColumns(null, "public", "mytable", "mycolumn");
        columns1.next();
        assertEquals(columns1.getInt("DATA_TYPE"), java.sql.Types.INTEGER);
        columns1.close();
//        Makes this test case pass
//        columns1.beforeFirst();

        ResultSet columns2 = metaData.getColumns(null, "public", "mytable", "mycolumn");
//        Makes this test case pass too
//        columns2.beforeFirst(); 
        columns2.next();
        assertEquals(columns2.getInt("DATA_TYPE"), java.sql.Types.INTEGER);
        columns2.close();
    }
```
This test case fails:
```
Running com.mockrunner.test.jdbc.MockDatabaseMetaDataTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.188 sec <<< FAILURE! - in com.mockrunner.test.jdbc.MockDatabaseMetaDataTest
testColumns2(com.mockrunner.test.jdbc.MockDatabaseMetaDataTest)  Time elapsed: 0.069 sec  <<< ERROR!
java.sql.SQLException: Current row invalid
	at com.mockrunner.mock.jdbc.MockResultSet.checkRowBounds(MockResultSet.java:2225)
	at com.mockrunner.mock.jdbc.MockResultSet.getObject(MockResultSet.java:797)
	at com.mockrunner.mock.jdbc.MockResultSet.getInt(MockResultSet.java:937)
	at com.mockrunner.test.jdbc.MockDatabaseMetaDataTest.testColumns2(MockDatabaseMetaDataTest.java:1359)
```

As the method MockPreparedStatement.executeQuery returns a clone of the resultsets, so the DatabaseMetaData.findMatchingDatabaseIdentifier should return a clone as well.

**Comment by cemartins** [comment]
Accepted pull request and released with version 2.0.3
